export const ACTION_RESIZE_WINDOW = "ACTION_RESIZE_WINDOW";
export const ACTION_GET_CARD_DIM = "ACTION_GET_CARD_DIM";
export const ACTION_CHANGE_LOGO_PATH = "ACTION_CHANGE_LOGO_PATH";
export const ACTION_GET_SLIDE_DIM = "ACTION_GET_SLIDE_DIM";
